### ISSUE TITLE
Error on running npm start

### ISSUE THREAD

**Issue by AdamTobias** [banunatina/biscuits#5]
I get the following error when I run npm start:

 [9] → npm start
.start-script: line 3: gshuf: command not found
cp: ./prompts//prompt.js: No such file or directory
mv: rename ./prompts//prompt.js to ./prompts//.prompt.js: No such file or directory

**Comment by banunatina** [comment]
Hey Adam - Biscuits uses GNU's shuffle, which requires coreutils.
Have you run `npm run setup`?

https://github.com/banunatina/biscuits#setup

**Comment by AdamTobias** [comment]
oops, no I had not.  I ran the setup command and now it works =)
